version: "2"
services:
  inspector-source:
    image: pgraemer/node-inspector:latest
    entrypoint: /bin/true

  app:
    extends:
      file: docker-compose.yml
      service: app
    command: node --debug server.js
    volumes_from:
      - inspector-source
    ports:
      - "3000:3000"

  inspector:
    image: pgraemer/node-inspector:latest
    network_mode: "service:app"
    command: --web-port=3000 --save-live-edit
    volumes_from:
      - app
